require "bundler/gem_tasks"
require "rake/testtask"
require 'rspec/core/rake_task'

task :bench do
  # todo
  # sh 'ruby -Ilib -r./test/shim test/bench.rb'
end

task :setup do
  unless Dir.exist?('node_modules/puppeteer') &&
     Dir.exist?('node_modules/jsdom') &&
     Dir.exist?('node_modules/canvas')
    `yarn add puppeteer@2.0.0`
    `yarn add jsdom@15.2.1`
    `yarn add canvas@2.6.0`
  end
end

RSpec::Core::RakeTask.new(:test) do |t|
  Rake::Task[:setup].invoke
  t.pattern = Dir.glob('spec/drivers/*_spec.rb')
  # t.rspec_opts = '--format documentation'
  # t.rspec_opts << ' more options'
  # t.rcov = true
end

RSpec::Core::RakeTask.new(:fail) do |t|
  Rake::Task[:setup].invoke
  t.pattern = Dir.glob('spec/drivers/*_spec.rb')
  t.rspec_opts = '--format documentation --fail-fast'
  # t.rspec_opts << ' more options'
  # t.rcov = true
end

task :default => :test

