dist: bionic
lanugage: ruby
rvm: 2.6.3
gemfile: ruby/Gemfile
script: cd ruby; bundle exec rake
before_install: nvm install 12.13.0
env:
  - LC_ALL=en_US.UTF-8
notifications:
  slack: isomorfeus:fkfbTBlQTpTgXaF7e0YOjWCG
