version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Run ruby test
          command: |
            ls -al
            cd ruby
            bundle install
            bundle exec rake