version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.5-stretch-node
    steps:
      - checkout
      - run:
          name: Run ruby test
          command: |
            ruby -v
            node -v
            cd ruby
            bundle install
            bundle exec rake